x-postgres-template: &postgres-template
  image: postgres:latest
  restart: "on-failure:1"
  healthcheck:
    test:
      [
        "CMD",
        "pg_isready",
        "-U",
        "${POSTGRES_USER:?error}",
        "-d",
        "${POSTGRES_DB:?error}",
      ]
    interval: 10s
    timeout: 10s
    retries: 3
  ports:
    - "${POSTGRES_PORT:-5432}:5432"

services:
  app:
    image: oomia/inssider-spring-template:latest
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      APP_PORT: ${APP_PORT:-8080}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:?error}
      POSTGRES_USER: ${POSTGRES_USER:?error}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "-q",
          "http://localhost:${APP_PORT:-8080}/actuator/health",
        ]
      interval: 10s
      timeout: 10s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    <<: *postgres-template
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?error}
      POSTGRES_USER: ${POSTGRES_USER:?error}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
