# == ENVIRONMENT VARIABLES ==
# POSTGRES_HOST=localhost | postgres
# POSTGRES_DB=dev
# POSTGRES_PORT=5432
# POSTGRES_USER=user
# POSTGRES_PASSWORD=user
# APP_PORT=8080

# == POSTGRES TEMPLATE ==
x-postgres-template: &postgres-template
  image: postgres:latest
  restart: "on-failure:1"
  environment:
    POSTGRES_DB: ${POSTGRES_DB:?error}
    POSTGRES_USER: ${POSTGRES_USER:?error}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
  healthcheck:
    test:
      ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]

# == SPRING APP TEMPLATE ==
x-app-template: &app-template
  environment:
    APP_PORT: ${APP_PORT:?error}
    POSTGRES_PORT: ${POSTGRES_PORT:?error}
    POSTGRES_DB: ${POSTGRES_DB:?error}
    POSTGRES_USER: ${POSTGRES_USER:?error}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
  healthcheck:
    test:
      [
        "CMD",
        "wget",
        "--spider",
        "-q",
        "http://localhost:${APP_PORT}/actuator/health",
      ]
  depends_on:
    postgres:
      condition: service_healthy

# == DOCKER COMPOSE ==
services:
  # == NO PROFILE ==
  postgres-dev:
    <<: *postgres-template
    env_file: [".env.example"]
    ports: ["${POSTGRES_PORT}:${POSTGRES_PORT}"]

  # == PROFILE: STAGE & PROD ==
  postgres:
    <<: *postgres-template
    profiles: [stage, prod]
    expose: ["${POSTGRES_PORT}"]

  # == PROFILE: STAGE ==
  app-stage:
    <<: *app-template
    profiles: [stage]
    environment:
      POSTGRES_HOST: localhost
    build:
      context: .
    ports: ["${APP_PORT}:8080"]

  # == PROFILE: PROD ==
  app:
    <<: *app-template
    profiles: [prod]
    environment:
      POSTGRES_HOST: postgres
    image: oomia/inssider-spring-template:latest
    ports: ["${APP_PORT}:8080"]
