server.port: 8080

spring.datasource.host: localhost

spring.jpa.hibernate:
  ddl-auto: create-drop
  show_sql: true
  format_sql: true

management.endpoints.web.exposure.include: "*"

logging.level.org.hibernate.SQL: debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: trace
logging.level.org.hibernate.tool.hbm2ddl: debug