server:
  port: ${APP_PORT}

spring:
  datasource:
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db}
    driver-class-name: org.postgresql.Driver
    host: ${POSTGRES_HOST}
    port: ${POSTGRES_PORT}
    db: ${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

spring.jpa.open-in-view: false

management.endpoints.web.exposure.include: health
