server.port: 8080

spring:
  datasource:
    host: ${POSTGRES_HOST:localhost}
    port: ${POSTGRES_PORT:5432}
    db: ${POSTGRES_DB:dev}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:user}

spring.jpa.hibernate:
  ddl-auto: update
  open-in-view: false
  show_sql: true
  format_sql: true

management.endpoints.web.exposure.include: "*"

logging.level.org.hibernate.SQL: debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: trace
logging.level.org.hibernate.tool.hbm2ddl: debug
