name: Deploy to EC2 with Docker Compose

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.AWS_INSTANCE_HOST }}
          username: ${{ github.repository_owner }}
          key: ${{ secrets.AWS_PERSONAL_PK }}
          port: ${{ secrets.AWS_SSH_PORT }}
          script: whoami
