name: Publish Docker image on Semver tag push

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: ${{ github.event.repository.name }}
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      GHCR_USERNAME: ${{ github.repository_owner }}
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}
            ghcr.io/${{ env.GHCR_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v3.6.0
      - uses: docker/setup-buildx-action@v3.10.0

      - name: Build and push
        if: ${{ steps.meta.outputs.tags != '' }}
        uses: docker/build-push-action@v6.17.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
