name: Docker-Based Testing

on:
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: "1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version-file: .java-version
          cache: "gradle"

      - uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Set up .env (dev profile)
        run: cp .env.example .env

      - name: Start Docker Compose (dev profile)
        run: docker compose --profile dev up -d

      - name: Run Gradle tests
        id: gradle-test
        run: |
          export $(grep -v '^#' .env | xargs)
          ./gradlew test --no-daemon

      - name: Docker clean-up
        run: docker compose down

      - name: Upload Test Report on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test

      - name: Show Workflow Duration on Success
        if: success()
        run: |
          START_TIME=$(date -d "${{ github.event.pull_request.created_at }}" +%s)
          END_TIME=$(date -u +%s)
          DURATION=$((END_TIME - START_TIME))
          echo "Took ${DURATION} seconds"
