name: Docker-Based Testing

on:
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version-file: .java-version

      - uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Set up .env (dev profile)
        run: cp .env.example .env

      - name: Start Docker Compose (dev profile)
        run: docker compose --profile dev up -d

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Gradle tests
        id: gradle-test
        run: |
          export $(grep -v '^#' .env | xargs)
          ./gradlew test

      - name: Docker clean-up
        run: docker compose down

      - name: Upload Test Report on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test

      - name: Show Workflow Duration on Success
        if: success()
        run: |
          START_TIME=$(date -d "${{ github.event.pull_request.created_at }}" +%s)
          END_TIME=$(date -u +%s)
          DURATION=$((END_TIME - START_TIME))
          echo "Took ${DURATION} seconds"
